// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BMS_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_StatusPage;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_BatteryBar;
void ui_event_BatteryArc(lv_event_t * e);
lv_obj_t * ui_BatteryArc;
lv_obj_t * ui_BatteryLabel;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_BatVoltLabel;
lv_obj_t * ui_CurVoltLabel;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_RemCapLabel;
lv_obj_t * ui_AvrgVolLabel;
lv_obj_t * ui_DeltaVolLabel;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label17;
lv_obj_t * ui_ChargeLabel;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_TMOSLabel;
lv_obj_t * ui_TBMSLabel;
lv_obj_t * ui_TBATLabel;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_DischargeLabel;
lv_obj_t * ui_BalanceLabel;
lv_obj_t * ui_Label20;
lv_obj_t * ui_AlarmLabel;
lv_obj_t * ui_CellsPage;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_CellLabel1;
lv_obj_t * ui_CellLabel2;
lv_obj_t * ui_CellLabel3;
lv_obj_t * ui_CellLabel4;
lv_obj_t * ui_CellLabel5;
lv_obj_t * ui_CellLabel6;
lv_obj_t * ui_CellLabel7;
lv_obj_t * ui_AlarmPage;
lv_obj_t * ui_AlarmLowCapacity;
lv_obj_t * ui_AlarmMosOverTemp;
lv_obj_t * ui_AlarmChargeOverVolt;
lv_obj_t * ui_AlarmDischargeUnderVolt;
lv_obj_t * ui_AlarmBatOverTemp;
lv_obj_t * ui_AlarmChargingOverCur;
lv_obj_t * ui_AlarmDischargeOverCur;
lv_obj_t * ui_AlarmCellDifferential;
lv_obj_t * ui_AlarmSensor2OverTemp;
lv_obj_t * ui_AlarmBatLowTemp;
lv_obj_t * ui_AlarmCellOverVolt;
lv_obj_t * ui_AlarmCellUnderVolt;
lv_obj_t * ui_Alarm309AProtection;
lv_obj_t * ui_Alarm309BProtection2;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label21;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label22;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BatteryArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000, &ui_Screen2_screen_init);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        event_screen2_loaded(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        event_back_btn_clicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
