// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BMS_UI

#ifndef _BMS_UI_UI_H
#define _BMS_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_StatusPage;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_BatteryBar;
void ui_event_BatteryArc(lv_event_t * e);
extern lv_obj_t * ui_BatteryArc;
extern lv_obj_t * ui_BatteryLabel;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BatVoltLabel;
extern lv_obj_t * ui_CurVoltLabel;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_RemCapLabel;
extern lv_obj_t * ui_AvrgVolLabel;
extern lv_obj_t * ui_DeltaVolLabel;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_ChargeLabel;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_TMOSLabel;
extern lv_obj_t * ui_TBMSLabel;
extern lv_obj_t * ui_TBATLabel;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_DischargeLabel;
extern lv_obj_t * ui_BalanceLabel;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_AlarmLabel;
extern lv_obj_t * ui_CellsPage;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_CellLabel1;
extern lv_obj_t * ui_CellLabel2;
extern lv_obj_t * ui_CellLabel3;
extern lv_obj_t * ui_CellLabel4;
extern lv_obj_t * ui_CellLabel5;
extern lv_obj_t * ui_CellLabel6;
extern lv_obj_t * ui_CellLabel7;
extern lv_obj_t * ui_AlarmPage;
extern lv_obj_t * ui_AlarmLowCapacity;
extern lv_obj_t * ui_AlarmMosOverTemp;
extern lv_obj_t * ui_AlarmChargeOverVolt;
extern lv_obj_t * ui_AlarmDischargeUnderVolt;
extern lv_obj_t * ui_AlarmBatOverTemp;
extern lv_obj_t * ui_AlarmChargingOverCur;
extern lv_obj_t * ui_AlarmDischargeOverCur;
extern lv_obj_t * ui_AlarmCellDifferential;
extern lv_obj_t * ui_AlarmSensor2OverTemp;
extern lv_obj_t * ui_AlarmBatLowTemp;
extern lv_obj_t * ui_AlarmCellOverVolt;
extern lv_obj_t * ui_AlarmCellUnderVolt;
extern lv_obj_t * ui_Alarm309AProtection;
extern lv_obj_t * ui_Alarm309BProtection2;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label21;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
