// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: BMS_UI

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags


    ui_StatusPage = lv_tabview_add_tab(ui_TabView1, "Status");
    lv_obj_clear_flag(ui_StatusPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_StatusPage);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -30);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_StatusPage);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 7);
    lv_obj_set_height(ui_Container2, 15);
    lv_obj_set_x(ui_Container2, 52);
    lv_obj_set_y(ui_Container2, -30);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBar = lv_bar_create(ui_StatusPage);
    lv_bar_set_value(ui_BatteryBar, 65, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 96);
    lv_obj_set_height(ui_BatteryBar, 44);
    lv_obj_set_x(ui_BatteryBar, 0);
    lv_obj_set_y(ui_BatteryBar, -30);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryBar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_BatteryBar, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBar, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xFFE106), LV_PART_INDICATOR | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_USER_2);

    ui_BatteryArc = lv_arc_create(ui_StatusPage);
    lv_obj_set_width(ui_BatteryArc, 110);
    lv_obj_set_height(ui_BatteryArc, 110);
    lv_obj_set_x(ui_BatteryArc, 0);
    lv_obj_set_y(ui_BatteryArc, -35);
    lv_obj_set_align(ui_BatteryArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteryArc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_BatteryArc, 50);
    lv_arc_set_bg_angles(ui_BatteryArc, 270, 269);
    lv_arc_set_mode(ui_BatteryArc, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_width(ui_BatteryArc, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0x00FF1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_BatteryArc, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_USER_1);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_INDICATOR | LV_STATE_USER_1);
    lv_obj_set_style_arc_color(ui_BatteryArc, lv_color_hex(0xFFE106), LV_PART_INDICATOR | LV_STATE_USER_2);
    lv_obj_set_style_arc_opa(ui_BatteryArc, 255, LV_PART_INDICATOR | LV_STATE_USER_2);

    lv_obj_set_style_bg_color(ui_BatteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabel, 0);
    lv_obj_set_y(ui_BatteryLabel, -35);
    lv_obj_set_align(ui_BatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryLabel, "100%");
    lv_obj_set_style_text_align(ui_BatteryLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -105);
    lv_obj_set_y(ui_Label9, -70);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Voltage");

    ui_Label10 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 105);
    lv_obj_set_y(ui_Label10, -70);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Current");

    ui_BatVoltLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_BatVoltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatVoltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatVoltLabel, -105);
    lv_obj_set_y(ui_BatVoltLabel, -30);
    lv_obj_set_align(ui_BatVoltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatVoltLabel, "30.10V");
    lv_obj_set_style_text_color(ui_BatVoltLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatVoltLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatVoltLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BatVoltLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_BatVoltLabel, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_BatVoltLabel, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_BatVoltLabel, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CurVoltLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_CurVoltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurVoltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurVoltLabel, 105);
    lv_obj_set_y(ui_CurVoltLabel, -30);
    lv_obj_set_align(ui_CurVoltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurVoltLabel, "-52.2A");
    lv_obj_set_style_text_color(ui_CurVoltLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurVoltLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurVoltLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CurVoltLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CurVoltLabel, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CurVoltLabel, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CurVoltLabel, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Label11 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label11, 70);
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -123);
    lv_obj_set_y(ui_Label11, 45);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Rem.Cap:");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label12, 70);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -123);
    lv_obj_set_y(ui_Label12, 65);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Avrg. Vol:");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label13, 70);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -123);
    lv_obj_set_y(ui_Label13, 85);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Delta Vol:");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RemCapLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_RemCapLabel, 55);
    lv_obj_set_height(ui_RemCapLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RemCapLabel, -58);
    lv_obj_set_y(ui_RemCapLabel, 45);
    lv_obj_set_align(ui_RemCapLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RemCapLabel, "97.0Ah");
    lv_obj_set_style_text_color(ui_RemCapLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RemCapLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RemCapLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RemCapLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AvrgVolLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_AvrgVolLabel, 55);
    lv_obj_set_height(ui_AvrgVolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvrgVolLabel, -58);
    lv_obj_set_y(ui_AvrgVolLabel, 65);
    lv_obj_set_align(ui_AvrgVolLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AvrgVolLabel, "3.765V");
    lv_obj_set_style_text_color(ui_AvrgVolLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AvrgVolLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AvrgVolLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AvrgVolLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeltaVolLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_DeltaVolLabel, 55);
    lv_obj_set_height(ui_DeltaVolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeltaVolLabel, -58);
    lv_obj_set_y(ui_DeltaVolLabel, 85);
    lv_obj_set_align(ui_DeltaVolLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeltaVolLabel, "0.076V");
    lv_obj_set_style_text_color(ui_DeltaVolLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeltaVolLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DeltaVolLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeltaVolLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label14, 55);
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -3);
    lv_obj_set_y(ui_Label14, 45);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "T_MOS:");
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label17, 65);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 92);
    lv_obj_set_y(ui_Label17, 45);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Charge:");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_ChargeLabel, 45);
    lv_obj_set_height(ui_ChargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeLabel, 149);
    lv_obj_set_y(ui_ChargeLabel, 45);
    lv_obj_set_align(ui_ChargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeLabel, "OFF");
    lv_obj_set_style_text_color(ui_ChargeLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ChargeLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label15, 55);
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -3);
    lv_obj_set_y(ui_Label15, 65);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "T_BMS:");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label16, 55);
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -3);
    lv_obj_set_y(ui_Label16, 85);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "T_BAT:");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TMOSLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_TMOSLabel, 35);
    lv_obj_set_height(ui_TMOSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TMOSLabel, 45);
    lv_obj_set_y(ui_TMOSLabel, 45);
    lv_obj_set_align(ui_TMOSLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TMOSLabel, "42C");
    lv_obj_set_style_text_color(ui_TMOSLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TMOSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TMOSLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TMOSLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TBMSLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_TBMSLabel, 35);
    lv_obj_set_height(ui_TBMSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TBMSLabel, 45);
    lv_obj_set_y(ui_TBMSLabel, 65);
    lv_obj_set_align(ui_TBMSLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TBMSLabel, "36C");
    lv_obj_set_style_text_color(ui_TBMSLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TBMSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TBMSLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TBMSLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TBATLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_TBATLabel, 35);
    lv_obj_set_height(ui_TBATLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TBATLabel, 45);
    lv_obj_set_y(ui_TBATLabel, 85);
    lv_obj_set_align(ui_TBATLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TBATLabel, "32C");
    lv_obj_set_style_text_color(ui_TBATLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TBATLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TBATLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TBATLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label18, 80);
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 85);
    lv_obj_set_y(ui_Label18, 65);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Dischrg:");
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label19, 65);
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 92);
    lv_obj_set_y(ui_Label19, 85);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Balance:");
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DischargeLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_DischargeLabel, 45);
    lv_obj_set_height(ui_DischargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DischargeLabel, 149);
    lv_obj_set_y(ui_DischargeLabel, 65);
    lv_obj_set_align(ui_DischargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DischargeLabel, "OFF");
    lv_obj_set_style_text_color(ui_DischargeLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DischargeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DischargeLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DischargeLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BalanceLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_BalanceLabel, 45);
    lv_obj_set_height(ui_BalanceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BalanceLabel, 149);
    lv_obj_set_y(ui_BalanceLabel, 85);
    lv_obj_set_align(ui_BalanceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BalanceLabel, "ON");
    lv_obj_set_style_text_color(ui_BalanceLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BalanceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BalanceLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BalanceLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_Label20, 150);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -4);
    lv_obj_set_y(ui_Label20, 27);
    lv_obj_set_align(ui_Label20, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label20, "Alarm:");
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmLabel = lv_label_create(ui_StatusPage);
    lv_obj_set_width(ui_AlarmLabel, 140);
    lv_obj_set_height(ui_AlarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmLabel, -3);
    lv_obj_set_y(ui_AlarmLabel, 27);
    lv_obj_set_align(ui_AlarmLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_AlarmLabel, "Normal");
    lv_obj_set_style_text_color(ui_AlarmLabel, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_AlarmLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_AlarmLabel, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_CellsPage = lv_tabview_add_tab(ui_TabView1, "Cells Voltage");
    lv_obj_clear_flag(ui_CellsPage, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label1, 16);
    lv_obj_set_height(ui_Label1, 20);
    lv_obj_set_x(ui_Label1, 10);
    lv_obj_set_y(ui_Label1, 10);
    lv_label_set_text(ui_Label1, "1");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label3, 16);
    lv_obj_set_height(ui_Label3, 20);
    lv_obj_set_x(ui_Label3, 10);
    lv_obj_set_y(ui_Label3, 52);
    lv_label_set_text(ui_Label3, "2");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label4, 16);
    lv_obj_set_height(ui_Label4, 20);
    lv_obj_set_x(ui_Label4, 10);
    lv_obj_set_y(ui_Label4, 94);
    lv_label_set_text(ui_Label4, "3");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label4, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label5, 16);
    lv_obj_set_height(ui_Label5, 20);
    lv_obj_set_x(ui_Label5, 10);
    lv_obj_set_y(ui_Label5, 136);
    lv_label_set_text(ui_Label5, "4");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label6, 16);
    lv_obj_set_height(ui_Label6, 20);
    lv_obj_set_x(ui_Label6, 160);
    lv_obj_set_y(ui_Label6, 30);
    lv_label_set_text(ui_Label6, "5");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label6, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label7, 16);
    lv_obj_set_height(ui_Label7, 20);
    lv_obj_set_x(ui_Label7, 160);
    lv_obj_set_y(ui_Label7, 114);
    lv_label_set_text(ui_Label7, "7");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_Label8, 16);
    lv_obj_set_height(ui_Label8, 20);
    lv_obj_set_x(ui_Label8, 160);
    lv_obj_set_y(ui_Label8, 72);
    lv_label_set_text(ui_Label8, "6");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0x5800FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CellLabel1 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel1, 40);
    lv_obj_set_y(ui_CellLabel1, 10);
    lv_label_set_text(ui_CellLabel1, "3.410V");
    lv_obj_add_state(ui_CellLabel1, LV_STATE_USER_2);       /// States
    lv_obj_set_style_text_color(ui_CellLabel1, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel1, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel1, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel2 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel2, 40);
    lv_obj_set_y(ui_CellLabel2, 52);
    lv_label_set_text(ui_CellLabel2, "3.450V");
    lv_obj_set_style_text_color(ui_CellLabel2, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel2, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel2, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel3 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel3, 40);
    lv_obj_set_y(ui_CellLabel3, 94);
    lv_label_set_text(ui_CellLabel3, "3.450V");
    lv_obj_set_style_text_color(ui_CellLabel3, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel3, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel3, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel3, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel4 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel4, 40);
    lv_obj_set_y(ui_CellLabel4, 136);
    lv_label_set_text(ui_CellLabel4, "3.450V");
    lv_obj_set_style_text_color(ui_CellLabel4, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel4, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel4, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel4, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel5 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel5, 190);
    lv_obj_set_y(ui_CellLabel5, 30);
    lv_label_set_text(ui_CellLabel5, "3.450V");
    lv_obj_set_style_text_color(ui_CellLabel5, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel5, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel5, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel5, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel6 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel6, 190);
    lv_obj_set_y(ui_CellLabel6, 72);
    lv_label_set_text(ui_CellLabel6, "3.450V");
    lv_obj_set_style_text_color(ui_CellLabel6, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel6, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel6, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel6, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_CellLabel7 = lv_label_create(ui_CellsPage);
    lv_obj_set_width(ui_CellLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CellLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CellLabel7, 190);
    lv_obj_set_y(ui_CellLabel7, 114);
    lv_label_set_text(ui_CellLabel7, "3.510V");
    lv_obj_add_state(ui_CellLabel7, LV_STATE_USER_1);       /// States
    lv_obj_set_style_text_color(ui_CellLabel7, lv_color_hex(0x00C603), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CellLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CellLabel7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CellLabel7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_opa(ui_CellLabel7, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_text_color(ui_CellLabel7, lv_color_hex(0x0003F8), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_text_opa(ui_CellLabel7, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_AlarmPage = lv_tabview_add_tab(ui_TabView1, "Alarm");
    lv_obj_add_flag(ui_AlarmPage, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_AlarmPage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags

    ui_AlarmLowCapacity = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmLowCapacity, 289);
    lv_obj_set_height(ui_AlarmLowCapacity, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_AlarmLowCapacity, "1. Low capacity alarm");
    lv_obj_clear_flag(ui_AlarmLowCapacity,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmLowCapacity, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmLowCapacity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmLowCapacity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmLowCapacity, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmMosOverTemp = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmMosOverTemp, 289);
    lv_obj_set_height(ui_AlarmMosOverTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmMosOverTemp, 0);
    lv_obj_set_y(ui_AlarmMosOverTemp, 15);
    lv_label_set_text(ui_AlarmMosOverTemp, "2. MOS overtemperature alarm");
    lv_obj_clear_flag(ui_AlarmMosOverTemp,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmMosOverTemp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmMosOverTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmMosOverTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmMosOverTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmChargeOverVolt = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmChargeOverVolt, 289);
    lv_obj_set_height(ui_AlarmChargeOverVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmChargeOverVolt, 0);
    lv_obj_set_y(ui_AlarmChargeOverVolt, 30);
    lv_label_set_text(ui_AlarmChargeOverVolt, "3. Charging overvoltage alarm");
    lv_obj_clear_flag(ui_AlarmChargeOverVolt,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmChargeOverVolt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmChargeOverVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmChargeOverVolt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmChargeOverVolt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmDischargeUnderVolt = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmDischargeUnderVolt, 289);
    lv_obj_set_height(ui_AlarmDischargeUnderVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmDischargeUnderVolt, 0);
    lv_obj_set_y(ui_AlarmDischargeUnderVolt, 45);
    lv_label_set_text(ui_AlarmDischargeUnderVolt, "4. Discharge undervoltage alarm");
    lv_obj_clear_flag(ui_AlarmDischargeUnderVolt,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmDischargeUnderVolt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmDischargeUnderVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmDischargeUnderVolt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmDischargeUnderVolt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmBatOverTemp = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmBatOverTemp, 289);
    lv_obj_set_height(ui_AlarmBatOverTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmBatOverTemp, 0);
    lv_obj_set_y(ui_AlarmBatOverTemp, 60);
    lv_label_set_text(ui_AlarmBatOverTemp, "5. Battery overtemperature alarm");
    lv_obj_clear_flag(ui_AlarmBatOverTemp,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmBatOverTemp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmBatOverTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmBatOverTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmBatOverTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmChargingOverCur = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmChargingOverCur, 289);
    lv_obj_set_height(ui_AlarmChargingOverCur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmChargingOverCur, 0);
    lv_obj_set_y(ui_AlarmChargingOverCur, 75);
    lv_label_set_text(ui_AlarmChargingOverCur, "6. Charging overcurrent alarm");
    lv_obj_clear_flag(ui_AlarmChargingOverCur,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmChargingOverCur, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmChargingOverCur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmChargingOverCur, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmChargingOverCur, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmDischargeOverCur = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmDischargeOverCur, 289);
    lv_obj_set_height(ui_AlarmDischargeOverCur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmDischargeOverCur, 0);
    lv_obj_set_y(ui_AlarmDischargeOverCur, 90);
    lv_label_set_text(ui_AlarmDischargeOverCur, "7. Discharge overcurrent alarm");
    lv_obj_clear_flag(ui_AlarmDischargeOverCur,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmDischargeOverCur, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmDischargeOverCur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmDischargeOverCur, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmDischargeOverCur, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmCellDifferential = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmCellDifferential, 289);
    lv_obj_set_height(ui_AlarmCellDifferential, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmCellDifferential, 0);
    lv_obj_set_y(ui_AlarmCellDifferential, 105);
    lv_label_set_text(ui_AlarmCellDifferential, "8. Cell differential voltage alarm");
    lv_obj_clear_flag(ui_AlarmCellDifferential,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmCellDifferential, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmCellDifferential, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmCellDifferential, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmCellDifferential, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmSensor2OverTemp = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmSensor2OverTemp, 289);
    lv_obj_set_height(ui_AlarmSensor2OverTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmSensor2OverTemp, 0);
    lv_obj_set_y(ui_AlarmSensor2OverTemp, 120);
    lv_label_set_text(ui_AlarmSensor2OverTemp, "9. Sensor 2 overtemperature alarm");
    lv_obj_clear_flag(ui_AlarmSensor2OverTemp,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmSensor2OverTemp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmSensor2OverTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmSensor2OverTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmSensor2OverTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmBatLowTemp = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmBatLowTemp, 289);
    lv_obj_set_height(ui_AlarmBatLowTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmBatLowTemp, 0);
    lv_obj_set_y(ui_AlarmBatLowTemp, 135);
    lv_label_set_text(ui_AlarmBatLowTemp, "10. Battery low temperature alarm");
    lv_obj_clear_flag(ui_AlarmBatLowTemp,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmBatLowTemp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmBatLowTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmBatLowTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmBatLowTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmCellOverVolt = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmCellOverVolt, 289);
    lv_obj_set_height(ui_AlarmCellOverVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmCellOverVolt, 0);
    lv_obj_set_y(ui_AlarmCellOverVolt, 150);
    lv_label_set_text(ui_AlarmCellOverVolt, "11. Cell overvoltage alarm");
    lv_obj_clear_flag(ui_AlarmCellOverVolt,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmCellOverVolt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmCellOverVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmCellOverVolt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmCellOverVolt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmCellUnderVolt = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_AlarmCellUnderVolt, 289);
    lv_obj_set_height(ui_AlarmCellUnderVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmCellUnderVolt, 0);
    lv_obj_set_y(ui_AlarmCellUnderVolt, 165);
    lv_label_set_text(ui_AlarmCellUnderVolt, "12. Cell undervoltage alarm");
    lv_obj_clear_flag(ui_AlarmCellUnderVolt,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_AlarmCellUnderVolt, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmCellUnderVolt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmCellUnderVolt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmCellUnderVolt, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm309AProtection = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_Alarm309AProtection, 289);
    lv_obj_set_height(ui_Alarm309AProtection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm309AProtection, 0);
    lv_obj_set_y(ui_Alarm309AProtection, 180);
    lv_label_set_text(ui_Alarm309AProtection, "13. 309_A Protection Alarm");
    lv_obj_clear_flag(ui_Alarm309AProtection,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarm309AProtection, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm309AProtection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarm309AProtection, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm309AProtection, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm309BProtection2 = lv_label_create(ui_AlarmPage);
    lv_obj_set_width(ui_Alarm309BProtection2, 289);
    lv_obj_set_height(ui_Alarm309BProtection2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Alarm309BProtection2, 0);
    lv_obj_set_y(ui_Alarm309BProtection2, 195);
    lv_label_set_text(ui_Alarm309BProtection2, "14. 309_B Protection Alarm");
    lv_obj_clear_flag(ui_Alarm309BProtection2,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Alarm309BProtection2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm309BProtection2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Alarm309BProtection2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Alarm309BProtection2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BatteryArc, ui_event_BatteryArc, LV_EVENT_ALL, NULL);

}
